server:
  port: 9121

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/DB_Student_Score?characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  username: root
  password: 1234

mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/*/**.xml
entity_package: com.shanzhu.sc.dto

